---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awssm-connect
    kind: ClusterSecretStore
  target:
    name: cluster-user-auth #create
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: admin
  data:
  - secretKey: cluster-user-auth #create
    remoteRef:
      key: weave-gitops #secret name
      property: password #name given from aws