---
global:
  resolve_timeout: 5m
route:
  group_by: ["alertname", "job"]
  group_interval: 10m
  group_wait: 1m
  receiver: discord
  repeat_interval: 12h
  routes:
    # - receiver: heartbeat
    #   group_interval: 5m
    #   group_wait: 0s
    #   matchers:
    #     - alertname =~ "Watchdog"
    #   repeat_interval: 5m
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor"
    - receiver: discord
      continue: true
      matchers:
        - severity = "critical"
inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
receivers:
  - name: heartbeat
    webhook_configs:
      secret_key_ref:
        name: alertmanager-discord-secret
        key: alertmanager-discord