---
global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 20s
  group_interval: 5m
  repeat_interval: 3h
  receiver: discord_webhook
    # - receiver: heartbeat
    #   group_interval: 5m
    #   group_wait: 0s
    #   matchers:
    #     - alertname =~ "Watchdog"
    #   repeat_interval: 5m
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor"
    - receiver: discord_webhook
      continue: true
      matchers:
        - severity = "critical"
inhibit_rules:
  - equal: ["alertname", "namespace"]
    source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
receivers:
  - name: 'discord_webhook'
    webhook_configs:
    - url: 'http://localhost:9094'
