apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "l2-pool"
spec:
  allowFirstLastIPs: "Yes"
  blocks:
    - start: "192.168.1.200"
      stop: "192.168.1.250"
#  - cidr: "192.168.1.0/24"  # Example: gives you 192.168.1.240-255
  # OR individual IPs:
  # - cidr: "192.168.1.240/32"
  # - cidr: "192.168.1.241/32"
