---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      qbittorrent:



        containers:
          app:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.1.2@sha256:31ac39705e31f7cdcc04dc46c1c0b0cdf8dc6f9865d4894efc097a33adc41524
            env:
              UMASK: "022"
              QBT_WEBUI_PORT: &port 8080

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 150m
                memory: 2048Mi
              limits:
                memory: 8192Mi
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: ["{{ .Release.Name }}.mambalab.live"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent
        advancedMounts:
          qbittorrent:
            app:
              - path: /config

      empty-config:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            port-forward:
              - path: /config

      media:
        type: persistentVolumeClaim
        existingClaim: qbittorrent-downloads
        globalMounts:
          - path: /media/downloads

