---
collections:
  - name: ansible.posix
    version: 2.0.0
  - name: ansible.utils
  renovate/ansible.utils-3.x
    version: 3.0.0
  - name: community.general
    version: 10.2.0
  - name: community.sops
    version: 2.0.1
  - name: kubernetes.core
    version: 6.0.0
  - name: onepassword.connect
    version: 2.3.0
roles:
  - name: xanmanning.k3s
    version: v3.4.4
