---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
  renovate/ansible.utils-3.x
    version: 3.0.0
  - name: community.general
    version: 12.3.0
  - name: community.sops
    version: 2.2.7
  - name: kubernetes.core
    version: 6.1.0
  - name: onepassword.connect
    version: 2.3.0
roles:
  - name: xanmanning.k3s
    version: v3.6.2
