---
spegel:
  appendMirrors: true
  containerdSock: /run/containerd/containerd.sock
  containerdRegistryConfigPath: /etc/cri/conf.d/hosts
service:
  registry:
    hostPort: 29999
serviceMonitor:
  enabled: true
grafanaDashboard:
  enabled: true
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "DoesNotExist"
        - matchExpressions:
            - key: "node-role.kubernetes.io/master"
              operator: "DoesNotExist"
