---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mambalab-live
  namespace: default
spec:
  secretName: mambalab-live-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "mambalab.live"
  dnsNames:
  - "mambalab.live"
  - "*.mambalab.live"