---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mealie
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/apps/selfhosted/mealie/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-apps-longhorn