---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ghostfolio
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s2
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: ghostfolio-redis
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/ghostfolio/ghostfolio
              tag: 2.186.0
            env:
              NODE_ENV: production
              REDIS_HOST: ghostfolio-redis.default.svc.cluster.local
              REDIS_PORT: 6379
              CREATE_ADMIN: "1"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: ghostfolio-pguser-ghostfolio
                    key: uri
              DEBUG: "1"
              LOG_DATE_TIME: "1"
              POLLING_SCHEDULER: "entry_frequency"
              POLLING_FREQUENCY: "15"
              RUN_MIGRATIONS: "1"
            envFrom:
              - secretRef:
                  name: ghostfolio-secret
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
    service:
      main:
        ports:
          http:
            port: 3333
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.mambalab.live
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Selfhosted
          gethomepage.dev/name: Ghostfolio
          gethomepage.dev/icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/ghostfolio.png
        hosts:
          - host: &host "cash.mambalab.live"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
