apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: homelab-notify
  namespace: flux-system
spec:
  summary: "dev cluster"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'