apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awssm-connect
    kind: ClusterSecretStore
  target:
    name: discord-url #create
    creationPolicy: Owner
  data:
  - secretKey: discord-url #create
    remoteRef:
      key: discord #secret name
      property: address