---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./discord.sops.yaml
  - ./discord-provider.yaml
  - ./discord-alert.yaml