apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-config
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # Specify the Longhorn storage class
  resources:
    requests:
      storage: 5Gi  # Request the desired storage size
