apiVersion: v1
data:
    rndc-algorithm: ENC[AES256_GCM,data:QyIwom+J3UPH2Bg=,iv:/YeACfkopeA5MsZXjL+LWeFq+Xy2AzpWfgt3wBBIhbE=,tag:lOOT9de67Qp/S8XEbaI2nA==,type:str]
    rndc-secret: ENC[AES256_GCM,data:KPLEuhmA3PAkSt/AXQo7H9D/xHEmAcSoLPogjcvGuLXtrJ4S/2QNBabW/5E=,iv:1Ga3WCNv4jPSdUX0q50XdqCP7ktyIzXpoF8qa2wrFeI=,tag:j5oUr0D4HXOtY1E2+YaOnw==,type:str]
kind: Secret
metadata:
    name: external-dns-bind-secret
    namespace: networking
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fema8gdj73k0hgk7s7h23uavm3mh3smst5eqq0sw8cfcakmxpa6q9pzftc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTjgrb0s1dVFKY0dNeTVo
            dm5UV1Q5ZStic3dDaEU2YUVQUXBKVGVzc3dRCkxNaDJFSFZDeVRUaVQxN1lneG1K
            SVBSVkdoK3hXdlY5SzVtMWFMZ3kzWFEKLS0tIFVXYVJ0Wk54NE5jdDk5b1FxSDU5
            Q2ZkRC9ZaTN1cWsvc0VESyswZUE2WTAKU/H5gVaiKX0uzvqMhN5sl3tq64U+za2I
            iZs/dRQKr/wsbISfqiX/Hv5X3sXUYPsE0GxZ1ko5vyaQce4atyq7JA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-26T22:54:08Z"
    mac: ENC[AES256_GCM,data:gSJrJQCKywuyBrrBsFpcewzWG2YbEspJI9ZSQyOf+XwC7hH/u7momdoHH93m5hYMWiNF7vynnq6oZcojrZWMVFQCUm1HhBKoIFv8lYCwGDuZd1RLbmOcffagQZORoWMEQx1rSP1Ynr8zeb9w+SQjTNULG6INfJ0geqrm+dg8Zcw=,iv:HqRescebVJaRh2aURA3E8gDV1w/PaD+NXMSezH6VTqc=,tag:SQeK1roPOI44kE2k0IUWgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
