apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-bind
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awssm-connect
    kind: ClusterSecretStore
  target:
    name: external-dns-bind-secret
    creationPolicy: Owner
  data:
  - secretKey: external-dns-bind-secret
    remoteRef:
      key: External-DNS-BIND-Secret
      property: EXTERNAL_DNS_RFC2136_TSIG_SECRET