apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-bind
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: awssm-connect
    kind: ClusterSecretStore
  target:
    name: external-dns-bind-secret #create
    creationPolicy: Owner
  data:
  - secretKey: external-dns-bind-secret #create
    remoteRef:
      key: External-DNS-BIND-Secret #secret name
      property: EXTERNAL_DNS_RFC2136_TSIG_SECRET #name given from aws