---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-bind
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: external-dns-bind
    provider: rfc2136
    env:
      - name: EXTERNAL_DNS_RFC2136_HOST
        value: "192.168.1.42"
      - name: EXTERNAL_DNS_RFC2136_PORT
        value: "53"
      - name: EXTERNAL_DNS_RFC2136_ZONE
        value: mambalab.live
      - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
        value: "true"
      - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
        value: external-key
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
        value: hmac-sha256
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        value: RGiygKwtJolsJVuZO/e7u8PxueH/qBl4ELARVpCEgGE=
    policy: sync
    sources: ["ingress", "service"]
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters: ["mambalab.live"]
    serviceMonitor:
      enabled: true

