---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mambalab-live
  namespace: networking
spec:
  secretName: mambalab-live-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "mambalab.live"
  dnsNames:
  - "mambalab.live"
  - "*.mambalab.live"