---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name libreddit
  namespace: selfhosted
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: *name
    controllers:
      main:
        containers:
          main:
            image:
              repository: libreddit/libreddit
              tag: latest@sha256:e79a5d6f6836b5a9351340433b1c26e8571ded943a5318f41ae939d314434c84
            env:
              TZ: "America/New_York"
              LIBREDDIT_DEFAULT_FRONT_PAGE: "default"
              LIBREDDIT_BANNER: "Lowkey"
              LIBREDDIT_DEFAULT_HIDE_HLS_NOTIFICATION: "on"
              LIBREDDIT_DEFAULT_THEME: "dracula"
              LIBREDDIT_DEFAULT_POST_SORT: "hot"
              LIBREDDIT_DEFAULT_LAYOUT: "clean"
              LIBREDDIT_DEFAULT_SHOW_NSFW: "on"
              LIBREDDIT_DEFAULT_USE_HLS: "on"
              LIBREDDIT_DEFAULT_BLUR_NSFW: "on"
              LIBREDDIT_SFW_ONLY: "off"
              LIBREDDIT_DEFAULT_AUTOPLAY_VIDEOS: "off"

            resources:
              requests:
                cpu: 50m
                memory: 150Mi
              limits:
                cpu: 200m
                memory: 300Mi
    service:
      main:
        ports:
          http:
            port: 8080

    route:
      app:
        hostnames: 
          - libreddit.mambalab.live
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
#    ingress:
#      main:
#        enabled: true
#        className: cilium
        annotations:
      #    external-dns.alpha.kubernetes.io/target: internal.mambalab.live
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Selfhosted
          gethomepage.dev/name: Libreddit
          gethomepage.dev/icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/libreddit.png
