---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: loki
      version: 5.23.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      limits_config:
        retention_period: 14d
        ingestion_rate_mb: 50
        ingestion_burst_size_mb: 1000
        per_stream_rate_limit: 5MB
        per_stream_rate_limit_burst: 20MB
      storage:
        type: filesystem
    singleBinary:
      replicas: 1
      persistence:
        size: 5Gi
        storageClass: longhorn
    gateway:
      image:
        registry: ghcr.io
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.42.0.0/16,192.168.1.0/24
        hosts:
          - host: &host loki.mambalab.live
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    test:
      enabled: false
    monitoring:
      serviceMonitor:
        enabled: false
        metricsInstance:
          enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false