---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: aws-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        # DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.database.svc.cluster.local/miniflux?sslmode=disable"
        # # Postgres Init
        # INIT_POSTGRES_DBNAME: miniflux
        # INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        # INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        # INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        # INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: aws
