---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s2
        namespace: flux-system

  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/miniflux/miniflux
              tag: 2.0.48@sha256:1aa8755118cf2865ee72521d87b8645080361fb75421314facb3766c0b0c07a3
            env:
              BASE_URL: https://miniflux.mambalab.live
              CREATE_ADMIN: "1"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: miniflux-pguser-miniflux
                    key: uri
              DEBUG: "1"
              LOG_DATE_TIME: "1"
              POLLING_SCHEDULER: "entry_frequency"
              POLLING_FREQUENCY: "15"
              RUN_MIGRATIONS: "1"
            envFrom:
              - secretRef:
                  name: miniflux-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
                  httpGet:
                    path: /healthcheck
                    port: 8080
            resources:
              requests:
                cpu: 12m
                memory: 64M
              limits:
                memory: 256M

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.mambalab.live
        hosts:
          - host: &host "miniflux.mambalab.live"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
