---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization
#namespace: default
#resources:
#  - ./externalsecret.yaml
#  - ./helmrelease.yaml
#  - ./postgrescluster.yaml
  # - ./awssecret.yaml

#secretGenerator:
#- name: aws
#  files:
#  - s3.conf

#generatorOptions:
#  disableNameSuffixHash: true
