---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: miniflux
  namespace: default
spec:
  postgresVersion: 15
  instances:
    - dataVolumeClaimSpec:
        storageClassName: longhorn-database
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

  users:
    - name: miniflux
      databases:
        - miniflux
      options: "SUPERUSER"

  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.47-2
      configuration:
      - secret:
          name: aws-secret
      #     key: AWS_ACCESS_KEY_ID
      # - secret:
      #     name: aws
      #     key: AWS_SECRET_ACCESS_KEY
      global:
        repo1-path: /pgbackrest/postgres-operator/miniflux/repo1
      repos:
      - name: repo1
        schedules:
          full: 30 2 * * *
        s3:
          bucket: "crunchy-postgres"
          endpoint: "s3.us-east-1.amazonaws.com"
          region: "us-east-1"
