---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-pihole
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  serviceAccountName: external-dns
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: external-dns-pihole
    provider: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://pi.hole
      - name: EXTERNAL_DNS_PIHOLE_TLS_SKIP_VERIFY
        value: true
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-secret
            key: pihole-secret
    registry: noop
    policy: upsert-only
    sources: ["ingress", "service"]
    txtOwnerId: default
    txtPrefix: k8s.
    domainFilters: ["mambalab.live"]
    serviceMonitor:
      enabled: true
    securityContext:
      fsGroup: 65534
    # podAnnotations:
    #   secret.reloader.stakater.com/reload: external-dns-bind-secret