---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./weaveworks.yaml
  - ./external-secrets.yaml
  - ./bjw-s-helm.yaml
  - ./grafana.yaml
  - ./actions-runner-controller.yaml
  - ./longhorn.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./tf-controller.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./cilium.yaml
