---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-paperless-redis
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/apps/default/paperless/redis"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-paperless
  namespace: flux-system
spec:
  interval: 10m
  path: ".cluster/apps/default/paperless/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-paperless-redis
    - name: cluster-apps-external-secrets-stores