---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: selfhosted
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        - Spotify:
            - icon: spotify.png
              href: 'http://open.spotify.com'
            - icon: reddit.png
              href: 'https://reddit.com'

    - Cloud:
        - CloudFlare:
            - icon: cloudflare.png
              href: https://dash.cloudflare.com
        - BackBlaze:
            - icon: backblaze.png
              href: https://secure.backblaze.com/b2_buckets.htm
        - AWS Console:
            - icon: aws.png
              href: https://aws.amazon.com/console/
        - Terraform Cloud:
            - icon: terraform.png
              href: https://app.terraform.io
        - Pushover:
            - icon: pushover.png
              href: https://client.pushover.net/

    - Clutch Vacations:
        - Clutch Homepage:
            - icon: virtualradarserver.png
              href: https://clutchvacations.com
        - Travel Agent Portal:
            - icon: virtualradarserver.png
              href: https://mytravelagentportal.com/
        - GoCCL:
            - icon: virtualradarserver.png
              href: https://goccl.com
    - Dev:
        - Github:
            - icon: github.png
              href: https://github.com/TMayweather
        - Kubesearch:
            - icon: kubernetes-dashboard.png
              href: https://kubesearch.dev

        - DevOps Books:
            - icon: mdi-book-open-variant
              href: https://github.com/rohitg00/DevOps_Books
  docker.yaml: ""
  kubernetes.yaml: |
    mode: default
  services.yaml: |
    - Monitoring:
        - Status:
            href: https://uptime.mambalab.live
            icon: uptime-kuma.png
            widget:
              type: uptimekuma
              url: https://uptime.mambalab.live
              fields: ["up", "down", "uptime", "incident"]

        - Prometheus:
            icon: prometheus.png
            href: https://prometheus.mambalab.live
            widget:
              type: prometheus
              url: https://prometheus.mambalab.live
              fields: ["targets_up", "targets_down", "targets_total"]
        - Grafana:
            icon: grafana.png
            description: Open-Source Observability Platform
            href: https://grafana.mambalab.live
            widget:
              type: grafana
              url: https://grafana.mambalab.live
              username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
              password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
              fields: ["dashboards", "datasources", "alertstriggered"]

    - Home:
        - Paperless:
            icon: paperless.png
            href: https://paperless.mambalab.live
            widget:
              type: paperlessngx
              url: https://paperless.mambalab.live
              key: {{HOMEPAGE_VAR_PAPERLESS_API_TOKEN}}
              fields: ["total", "inbox"]

        - Miniflux:
            icon: miniflux.png
            href: https://miniflux.mambalab.live
            widget:
              type: miniflux
              url: https://miniflux.mambalab.live
              key: {{HOMEPAGE_VAR_MINIFLUX_API_TOKEN}}
              fields: ["unread", "read"]

        - Mealie:
            icon: mealie.png
            href: https://mealie.mambalab.live
            widget:
              type: mealie
              url: https://mealie.mambalab.live
              key: {{HOMEPAGE_VAR_MEALIE_API_TOKEN}}
              fields: ["recipes", "users", "categories", "tags"]
  settings.yaml: |
    title: Mayweather Homepage
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/plume.png
    theme: dark
    color: emerald
    headerStyle: clean
    layout:
      Media:
        style: row
        columns: 2
        icon: mdi-play-circle
      Infrastructure:
        style: row
        columns: 3
        icon: mdi-server
      Home:
        style: column
        icon: mdi-home-analytics
      Monitoring:
        style: column
        icon: mdi-chart-line
      Cloud:
        style: column
        icon: mdi-cloud
      Dev:
        style: row
        columns: 2
        icon: mdi-language-python
      Clutch Vacations:
        style: row
        columns: 2
        icon: mdi-wallet-travel
    providers:
      longhorn:
        url: https://longhorn.mambalab.live
  widgets.yaml: |
    - search:
        provider: [duckduckgo]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - longhorn:
        expanded: false
        total: true
        labels: true
        nodes: false
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
