---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: selfhosted
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        - Spotify:
            - icon: spotify.png
              href: 'http://open.spotify.com'
        - Sports:
            - icon: slice.png
              href: 'https://sportsurge.io'
        - Movies & TV:
            - icon: streama.png
              href: 'https://moviestowatch.tv'
        - Anime:
            - icon: shiori.png
              href: 'https://aniwave.to'

    - Cloud:
        - CloudFlare:
            - icon: cloudflare.png
              href: https://dash.cloudflare.com
        - BackBlaze:
            - icon: backblaze.png
              href: https://secure.backblaze.com/b2_buckets.htm
        - AWS Console:
            - icon: aws.png
              href: https://aws.amazon.com/console/
        - Terraform Cloud:
            - icon: terraform.png
              href: https://app.terraform.io
        - Pushover:
            - icon: pushover.png
              href: https://client.pushover.net/

    - Clutch Vacations:
        - Clutch Homepage:
            - icon: yacht-light.png
              href: https://clutchvacations.com
        - Travel Portal:
            - icon: synology-photo-station.png
              href: https://mytravelagentportal.com/
        - GoCCL:
            - icon: virtualradarserver.png
              href: https://goccl.com
        - Cruising Power:
            - icon: yacht-light.png
              href: https://secure.cruisingpower.com

    - Dev:
        - Github:
            - icon: git.png
              href: https://github.com/TMayweather
        - Kubesearch:
            - icon: kubernetes-dashboard.png
              href: https://kubesearch.dev

        - DevOps Books:
            - icon: booksonic.png
              href: https://github.com/rohitg00/DevOps_Books
  docker.yaml: ""
  kubernetes.yaml: |
    mode: default
  services.yaml: |
    - Monitoring:
        - Uptime Kuma:
            href: https://uptime.mambalab.live
            icon: uptime-kuma.png
            description: Status Monitor
            widget:
              type: uptimekuma
              url: https://uptime.mambalab.live
              fields: ["up", "down", "uptime", "incident"]
              slug: services
        - Prometheus:
            icon: prometheus.png
            description: Systems Monitoring and Alerting Toolkit
            href: https://prometheus.mambalab.live
            widget:
              type: prometheus
              url: https://prometheus.mambalab.live
              fields: ["targets_up", "targets_down", "targets_total"]
        - Grafana:
            icon: grafana.png
            description: Observability Platform
            href: https://grafana.mambalab.live
            widget:
              type: grafana
              url: https://grafana.mambalab.live
              username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
              password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
              fields: ["dashboards", "datasources", "alertstriggered"]

    - Home:
         - Mealie:
            icon: mealie.png
            href: https://mealie.mambalab.live
            description: Shopping Lists and Recipes Aggregate
            widget:
              type: mealie
              url: https://mealie.mambalab.live
              key: {{HOMEPAGE_VAR_MEALIE_API_TOKEN}}
              fields: ["recipes", "users", "categories", "tags"]
         - Paperless:
            icon: paperless.png
            href: https://paperless.mambalab.live
            description: Document Management System
            widget:
              type: paperlessngx
              url: https://paperless.mambalab.live
              key: {{HOMEPAGE_VAR_PAPERLESS_API_TOKEN}}
              fields: ["total", "inbox"]


    - Selfhosted:
        - Miniflux:
            icon: miniflux.png
            href: https://miniflux.mambalab.live
            description: RSS Feed Reader
            widget:
              type: miniflux
              url: https://miniflux.mambalab.live
              key: {{HOMEPAGE_VAR_MINIFLUX_API_TOKEN}}
              fields: ["unread", "read"]

  settings.yaml: |
    title: Mayweather Homepage
    favicon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/selfhosted-light.png
    theme: dark
    color: emerald
    headerStyle: clean
    layout:
      Home:
        style: row
        columns: 2
        icon: mdi-home-analytics
      Selfhosted:
        style: row
        columns: 2
        icon: mdi-server
      Monitoring:
        style: row
        icon: mdi-chart-line
        columns: 2
      Media:
        style: column
        icon: mdi-play-circle
      Cloud:
        style: column
        icon: mdi-cloud
      Dev:
        style: column
        icon: mdi-language-python
      Clutch Vacations:
        style: column
        icon: mdi-wallet-travel
    providers:
      longhorn:
        url: https://longhorn.mambalab.live
  widgets.yaml: |
    - search:
        provider: [duckduckgo]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          label: mambalab
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - longhorn:
        expanded: false
        total: true
        labels: true
        nodes: false
    - datetime:
        text_size: l
        format:
          dateStyle: short
          timeStyle: short
          hourCycle: h23
