---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: selfhosted
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        - Spotify:
            - icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/navidrome.png
              href: 'http://open.spotify.com'
        - Sports:
            - icon: slice.png
              href: 'https://sportsurge.io'
        - Movies & TV:
            - icon: streama.png
              href: 'https://movies2watch.to'
        - Live TV:
            - icon: streama.png
              href: 'https://thetvapp.to/'
        - Movies & TV:
            - icon: streama.png
              href: 'https://lookmovie2.to'
        - Anime:
            - icon: shiori.png
              href: 'https://miruro.tv'

    - Cloud:
        - CloudFlare:
            - icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/cloudflare.png
              href: https://dash.cloudflare.com
        - BackBlaze:
            - icon: backblaze.png
              href: https://secure.backblaze.com/b2_buckets.htm
        - AWS Console:
            - icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/amazon.png
              href: https://aws.amazon.com/console/
        - Terraform Cloud:
            - icon: terraform.png
              href: https://app.terraform.io
        - Pushover:
            - icon: pushover.png
              href: https://client.pushover.net/

    - Clutch Vacations:
        - Clutch Homepage:
            - icon: yacht-light.png
              href: https://clutchvacations.com
        - Travel Portal:
            - icon: synology-photo-station.png
              href: https://mytravelagentportal.com/
        - GoCCL:
            - icon: virtualradarserver.png
              href: https://goccl.com
        - Cruising Power:
            - icon: yacht-light.png
              href: https://secure.cruisingpower.com

    - Dev:
        - Github:
            - icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/github.png
              href: https://github.com/TMayweather
        - Kubesearch:
            - icon: kubernetes-dashboard.png
              href: https://kubesearch.dev

        - DevOps Books:
            - icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/bookstack.png
              href: https://github.com/rohitg00/DevOps_Books
  docker.yaml: ""
  kubernetes.yaml: |
    mode: default
  services.yaml: |
    - Monitoring:
        - Uptime Kuma:
            href: https://uptime.mambalab.live
            icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/uptime-kuma.png
            description: Status Monitor
            widget:
              type: uptimekuma
              url: https://uptime.mambalab.live
              fields: ["up", "down", "uptime", "incident"]
              slug: services
        - Prometheus:
            icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/prometheus.png
            description: Systems Monitoring and Alerting Toolkit
            href: https://prometheus.mambalab.live
            widget:
              type: prometheus
              url: https://prometheus.mambalab.live
              fields: ["targets_up", "targets_down", "targets_total"]
        - Grafana:
            icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/grafana.png
            description: Observability Platform
            href: https://grafana.mambalab.live
            widget:
              type: grafana
              url: https://grafana.mambalab.live
              username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
              password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
              fields: ["dashboards", "datasources", "alertstriggered"]

        - PiHole:
            icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/pihole.png
            href: http://192.168.1.43
            description: DNS Server & Ad-Blocker
            widget:
              type: pihole
              url: http://192.168.1.43
              key: {{HOMEPAGE_VAR_PIHOLE_API_TOKEN}}
              fields: ["queries", "blocked", "blocked_percent", "gravity"]

    - Home:
         - Mealie:
            icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/mealie.png
            href: https://mealie.mambalab.live
            description: Shopping Lists and Recipes Aggregate
            widget:
              type: mealie
              url: https://mealie.mambalab.live
              key: {{HOMEPAGE_VAR_MEALIE_API_TOKEN}}
              fields: ["recipes", "users", "categories", "tags"]
         - Paperless:
            icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/paperlessngx.png	
            href: https://paperless.mambalab.live
            description: Document Management System
            widget:
              type: paperlessngx
              url: https://paperless.mambalab.live
              key: {{HOMEPAGE_VAR_PAPERLESS_API_TOKEN}}
              fields: ["total", "inbox"]

    - Selfhosted:
        - Miniflux:
            icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/miniflux.png
            href: https://miniflux.mambalab.live
            description: RSS Feed Reader
            widget:
              type: miniflux
              url: https://miniflux.mambalab.live
              key: {{HOMEPAGE_VAR_MINIFLUX_API_TOKEN}}
              fields: ["unread", "read"]
  settings.yaml: |
    title: Mayweather Homepage
    favicon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/selfhosted-light.png
    theme: dark
    color: gray
    headerStyle: clean
    background:
      image: https://i.imgur.com/5DJSIvq.png
      blur: sm
    hideVersion: true
    statusStyle: "dot"
    layout:
      Home:
        style: row
        columns: 2
        icon: mdi-home-analytics
      Selfhosted:
        style: row
        columns: 2
        icon: mdi-server
      Monitoring:
        style: row
        icon: mdi-chart-line
        columns: 2
      Media:
        style: column
        icon: mdi-play-circle
      Cloud:
        style: column
        icon: mdi-cloud
      Dev:
        style: column
        icon: mdi-language-python
      Clutch Vacations:
        style: column
        icon: mdi-wallet-travel
    providers:
      longhorn:
        url: https://longhorn.mambalab.live
  widgets.yaml: |
    - search:
        provider: [duckduckgo]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          label: mambalab
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - longhorn:
        expanded: true
        total: true
        labels: true
        nodes: false
    - datetime:
        text_size: l
        format:
          dateStyle: short
          timeStyle: short
          hourCycle: h23
  
  custom.css: |
    @import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz@9..40&family=Fira+Code&family=Poppins&family=Source+Code+Pro&family=Work+Sans&display=swap');

    .theme-gray {
            font-family: 'DM Sans', sans-serif;

    	    /* DRACULA COLORS */
            --dracula-background: #282a36;
            --dracula-background-dark: #15161d;
            --dracula-foreground: #44475a;
            --dracula-text: #f8f8f2;
            --dracula-slate: #6272a4;
            --dracula-cyan: #8be9fd;
            --dracula-green: #50fa7ae8;
            --dracula-orange: #ffb86c;
            --dracula-pink: #ff79c6;
            --dracula-purple: #bd93f9;
            --dracula-red: #ff5555;
            --dracula-yellow: #f1fa8c;

            /* Theme preset colors */
            --color-50: 249 250 251;
            --color-100: 243 244 246;
            --color-200: 248 248 242; /* Text Color - use Dracula text color */
            --color-300: 209 213 219;
            --color-400: 156 163 175;
            --color-500: 107 114 128;
            --color-600: 75 85 99;
            --color-700: 55 65 81;
            --color-800: 40 42 54; /* Background color - use Dracula theme color */
            --color-900: 21 22 29; /* Dracula specific */
            --color-logo-start: 156 163 175;
            --color-logo-stop: 55 65 81;

            --standard-bg: #44475a8e;

            /* INFO WIDGET COLORS */
            --info-widgets: var(--dracula-purple);
            --resource-bar-bg: var(--standard-bg);
            --resource-bar-fg: var(--dracula-green);

            --widget-border: var(--dracula-foreground);

            /* SERVICES COLORS */
            --service-group: var(--dracula-purple);

            --service-name: var(--dracula-text);
            --service-description: var(--dracula-purple);

            --service-block-bg: #232530;
            --service-block-text: var(--dracula-pink);

            /* BOOKMARKS COLORS */
            --bookmark-group: var(--dracula-purple);
            --bookmark-group-icon: var(--dracula-purple);
            --bookmark-icon-bg: #44475a60;
            --bookmark-icon: var(--dracula-purple);
            --bookmark-name: var(--dracula-text);

            /* ALL CARD COLORS */
            --card-color: #44475a46;
            --card-color-hover: #44475a91;

            /* FOOTER COLORS */
            --footer-items: var(--dracula-pink);

            /* FOOTER COLORS */
            --scrollbar-fg: var(--dracula-purple);
            --scrollbar-bg: var(--standard-bg);

            /*Class color values */
            .service-tags .dark\:bg-theme-900\/50 {
                    background-color: rgb(var(--color-900) / 0.3) !important
            }
            .bg-theme-800\/70 {
                    background-color: #50fa7b !important;
            }
            #information-widgets {
                    border-color: var(--widget-border);
            }

            #information-widgets * {
                    color: var(--info-widgets);
            }

            #information-widgets .information-widget-logo {
                    height: 40px;
                    width: 40px;
                    margin-left: 10px;
            }

            .resource-usage {
                    background-color: var(--resource-bar-bg);
            }

            .resource-usage > div {
                    background-color: var(--resource-bar-fg);
            }

            .service-group-icon > div {
                    background: var(--service-group) !important; /* group label ICON color */
            }

            .service-group-name {
                    color: var(--service-group); /* group label NAME color */
            }

            .services-group > button > svg {
                    color: var(--service-group); /* group label EXPAND/COLLAPSE ICON color */
            }

            .service-card {
                    background-color: var(--card-color);
            }

            .service-card:hover {
                    background-color: var(--card-color-hover);
            }

            .service-name.text-sm {
                    font-size: 0.95rem;
                    color: var(--service-name);
            }

            .service-description.text-xs {
                    font-size: 0.75rem;
                    color: var(--service-description);
            }

            .service img {
                    border-radius: 25%;
            }

            .service-block {
                    background: var(--service-block-bg);
            }

            .service-block .uppercase {
                    color: var(--service-block-text);
            }

            .service-block .font-thin {
                    color: var(--dracula-text);
            }


            .bookmark-group-name {
                    color: var(--bookmark-group);
            }

            .bookmark-icon {
                    background-color: var(--bookmark-icon-bg);
            }

            .bookmark-icon > div > div {
                    background: var(
                            --bookmark-icon
                    ) !important; /* If using si or md icons, make default purple */
            }

            .bookmark-name.text-xs {
                    font-size: 0.85rem;
                    color: var(--bookmark-name);
            }

            li.bookmark > a {
                    background-color: var(--card-color);
            }

            li.bookmark > a:hover {
                    background-color: var(--card-color-hover);
            }

            #dracula-calendar .flex.justify-between.flex-wrap span {
                    color: var(--dracula-purple);
            }

            #footer svg {
                    color: var(--footer-items);
            }


          * {
                    --scrollbar-thumb: var(--scrollbar-fg);
                    --scrollbar-track: var(--scrollbar-bg);
            }


            .bg-amber-500 {
                    background-color: var(--dracula-orange);
            }

            .bg-black {
                    background-color: rgb(0 0 0);
            }

            .bg-blue-500 {
                    background-color: var(--dracula-cyan);
            }

            .bg-cyan-500 {
                    background-color: var(--dracula-cyan);
            }

            .bg-emerald-500 {
                    background-color: var(--dracula-green);
            }

            .bg-fuchsia-500 {
                    background-color: var(--dracula-pink);
            }

            .bg-gray-500 {
                    background-color: var(--dracula-foreground);
            }

            .bg-green-500 {
                    background-color: var(--dracula-green);
            }

            .bg-indigo-500 {
                    background-color: var(--dracula-purple);
            }

            .bg-lime-500 {
                    background-color: var(--dracula-green);
            }

            .bg-neutral-500 {
                    background-color: rgb(115 115 115);
            }

            .bg-orange-400 {
                    background-color: var(--dracula-orange);
            }

            .bg-orange-500 {
                    background-color: var(--dracula-orange);
            }

            .bg-pink-500 {
                    background-color: var(--dracula-pink);
            }

            .bg-purple-500 {
                    background-color: var(--dracula-purple);
            }

            .bg-red-500 {
                    background-color: var(--dracula-red);
            }

            .bg-rose-100 {
                    background-color: rgb(255, 205, 205);
            }

            .bg-rose-500 {
                    background-color: var(--dracula-red);
            }

            .bg-rose-900\/80 {
                    background-color: var(--dracula-red);
            }

            .bg-sky-500 {
                    background-color: var(--dracula-cyan);
            }

            .bg-slate-500 {
                    background-color: var(--dracula-slate);
            }

            .bg-stone-500 {
                    background-color: rgb(120 113 108);
            }

            .bg-teal-500 {
                    background-color: rgb(20 184 166);
            }

            .bg-violet-500 {
                    background-color: var(--dracula-purple);
            }

            .bg-white {
                    background-color: var(--dracula-text);
            }

            .bg-white\/50 {
                    background-color: hsla(250.2, 52.8%, 17.5%, 0.5);
            }

            .bg-yellow-500 {
                    background-color: var(--dracula-yellow);
            }

            .bg-zinc-500 {
                    background-color: rgb(113 113 122);
            }

            .text-amber-800 {
                    color: var(--dracula-orange);
            }

            .text-black {
                    color: rgb(0 0 0);
            }

            .text-black\/20 {
                    color: rgba(0, 0, 0, 0.2);
            }

            .text-blue-500\/80 {
                    color: rgba(139, 233, 253, 0.8);
            }

            .text-emerald-300 {
                    color: var(--dracula-green);
            }

            .text-emerald-500\/80 {
                    color: rgba(80, 250, 123, 0.8);
            }

            .text-gray-500 {
                    color: rgb(107 114 128);
            }

            .text-green-500 {
                    color: var(--dracula-green);
            }

            .text-orange-400\/50 {
                   color: rgba(255, 184, 108, 0.5);
            }

            .text-red-400 {
                   color: var(--dracula-red);
            }

            .text-red-500 {
                   color: var(--dracula-red);
            }

            .text-red-500\/40 {
                   color: rgba(255, 85, 85, 0.4);
            }

            .text-rose-300 {
                   color: var(--dracula-red);
            }

            .text-rose-500 {
                   color: var(--dracula-red);
            }

            .text-rose-500\/80 {
                   color: rgba(255, 85, 85, 0.8);
            }

            .text-rose-900 {
                   color: var(--dracula-red);
            }

            .text-white {
                   color: var(--dracula-text);
            }
    } 
