---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: selfhosted
  labels:
    app.kubernetes.io/name: homepage
data:
  bookmarks.yaml: |
    - Media:
        - YouTube:
            - icon: youtube.png
              href: 'https://youtube.com/feed/subscriptions'
        - Spotify:
            - icon: spotify.png
              href: 'http://open.spotify.com'
            - icon: reddit.png
              href: 'https://reddit.com'

    - Cloud:
        - CloudFlare:
            - icon: cloudflare.png
              href: https://dash.cloudflare.com
        - BackBlaze:
            - icon: backblaze.png
              href: https://secure.backblaze.com/b2_buckets.htm
        - AWS Console:
            - icon: aws.png
              href: https://aws.amazon.com/console/
        - Terraform Cloud:
            - icon: terraform.png
              href: https://app.terraform.io
        - Pushover:
            - icon: pushover.png
              href: https://client.pushover.net/

    - Clutch Vacations:
        - Clutch Homepage:
            - icon: virtualradarserver.png
              href: https://clutchvacations.com
        - Travel Agent Portal:
            - icon: virtualradarserver.png
              href: https://mytravelagentportal.com/
  docker.yaml: ""
  kubernetes.yaml: |
    mode: default
  services.yaml: |
    - Monitoring:
        - Status:
            href: https://uptime.local.mambalab.live
            icon: uptime-kuma.png
            widget:
              type: uptimekuma
              url: http://uptime.local.mambalab.live
              slug: services

        - Grafana:
            icon: grafana.png
            description: Open-Source Observability Platform
            href: http://grafana.mambalab.live
            widget:
              type: grafana
              url: http://grafana.mambalab.live
              username: {{.GRAFANA_USERNAME}}
              password: {{.GRAFANA_PASSWORD}}
              fields: ["dashboards", "datasources", "alertstriggered"]

    - Home:
        - Actual:
            href: https://actual.mambalab.live
            icon: actual.png

        - Paperless:
            icon: paperless.png
            href: https://paperless.mambalab.live
            widget:
              type: paperless
              url: https://paperless.mambalab.live
              key: {{.PAPERLESS_API_TOKEN}}
              fields: ["totals", "inbox"]
  settings.yaml: |
    title: Mayweather Homepage
    theme: dark
    color: emerald
    headerStyle: clean
    layout:
      Media:
        style: row
        columns: 2
        icon: mdi-play-circle
      Infrastructure:
        style: row
        columns: 3
        icon: mdi-server
      Storage:
        style: row
        columns: 2
        icon: mdi-desktop-tower
      Home:
        style: column
        icon: mdi-home-analytics
      Monitoring:
        style: column
        icon: mdi-chart-line
    providers:
      longhorn:
        url: https://longhorn.mambalab.live
  widgets.yaml: |
    - search:
        provider: [duckduckgo]]
        focus: false
        target: _blank
    - greeting:
        text_size: l
        text: "Hang in there, you got this.."
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: false
          showLabel: true
    - longhorn:
        expanded: false
        total: true
        labels: true
        nodes: false
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
