---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        # HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        # HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARED_K8S_TUNNEL_ID }}"
        # HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_HOMEPAGE_TOKEN }}"
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_USERNAME }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_PASSWORD }}"

        HOMPAGE_VAR_MEALIE_API_TOKEN: "{{ .MEALIE_API_TOKEN }}"
        HOMEPAGE_VAR_PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
        HOMEPAGE_VAR_MINIFLUX_API_TOKEN: "{{ .MINIFLUX_API_TOKEN }}"
        HOMEPAGE_VAR_PIHOLE_API_TOKEN: "{{ .PIHOLE_API_TOKEN }}"
  dataFrom:
    - extract:
        key: homepage-secret
