---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## Non Cluster resources
        # HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID: "{{ .CLOUDFLARE_ACCOUNT_ID }}"
        # HOMEPAGE_VAR_CLOUDFLARED_TUNNELID: "{{ .CLOUDFLARED_K8S_TUNNEL_ID }}"
        # HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN: "{{ .CLOUDFLARE_HOMEPAGE_TOKEN }}"
        HOMEPAGE_VAR_GRAFANA_USERNAME: "{{ .GRAFANA_USERNAME }}"
        HOMEPAGE_VAR_GRAFANA_PASSWORD: "{{ .GRAFANA_PASSWORD }}"


        HOMEPAGE_VAR_PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
        HOMEPAGE_VAR_MINIFLUX_API_TOKEN: "{{ .MINIFLUX_API_TOKEN }}"
  dataFrom:
    # - extract:
    #     key: cloudflare
    # - extract:
    #     key: cloudflare-tunnel-id
    - extract:
        key: miniflux
    - extract:
        key: paperless
    - extract:
        key: grafana
