apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
- ./helmrelease.yaml

secretGenerator:
- name: pgo-s3-creds
  files:
  - config/s3.conf

generatorOptions:
  disableNameSuffixHash: true
