apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi    # Adjust size as required

