# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: selfhosted
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      n8n:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: ghcr.io/n8n-io/n8n
              tag: 1.89.2
            env:
              DB_SQLITE_VACUUM_ON_STARTUP: true
              EXECUTIONS_DATA_PRUNE: true
              EXECUTIONS_DATA_MAX_AGE: 7
              EXECUTIONS_DATA_PRUNE_MAX_COUNT: 50000
              GENERIC_TIMEZONE: "America/New_York"
              N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: false
              N8N_PROTOCOL: "https"
              N8N_PORT: &port 8080
              N8N_HOST: &host n8n.mambalab.live
              WEBHOOK_URL: "https://n8n-webhook.mambalab.live/"
              N8N_LOG_LEVEL: info
              N8N_LOG_OUTPUT: console
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 2Gi
    service:
      app:
        controller: n8n
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.mambalab.live
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
      # New webhook ingress configuration
      webhooks:
        enabled: true
        className: external
        hosts:
          - host: n8n-webhook.mambalab.live
            paths:
              - path: /webhook
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: n8n
        advancedMounts:
          n8n:
            app:
              - path: /home/node/.n8n
