apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteOnce  # Most common access mode
  resources:
    requests:
      storage: 5Gi   # Request 5 gigabytes of storage
  storageClassName: local-path  # Use default storage
