---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole-kubernetes
      version: 2.17.0
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    serviceWeb:
      loadBalancerIP: 192.168.1.232
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 192.168.1.232
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
      - 192.168.1.42
      - 1.1.1.1
