---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-home-ops
  namespace: actions-runner-system
spec:
  interval: 10m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 4
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: arc-runner-set-home-ops
    githubConfigUrl: https://github.com/TMayweather/home-ops
    minRunners: 1
    maxRunners: 3
    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: ubuntu-24.04
            command: ["/home/runner/run.sh"]
        #     volumeMounts:
        #       - name: data
        #         mountPath: /var/lib/dagger
        #       - name: socket
        #         mountPath: /var/run/buildkit
        #     env:
        #       - name: _EXPERIMENTAL_DAGGER_RUNNER_HOST
        #         value: "unix:///var/run/buildkit/buildkitd.sock"

        # volumes:
        #   - name: data
        #     hostPath:
        #       path: /var/lib/dagger
        #   - name: socket
        #     hostPath:
        #       path: /var/run/dagger

        # securityContext:
        #   runAsUser: 0
        #   runAsGroup: 568
        #   fsGroup: 568
        #   fsGroupChangePolicy: "OnRootMismatch"  
  valuesFrom:
    - kind: Secret
      name: actions-runner-controller-auth-secret
      valuesKey: github_app_id
      targetPath: githubConfigSecret.github_app_id
    - kind: Secret
      name: actions-runner-controller-auth-secret
      valuesKey: github_app_installation_id
      targetPath: githubConfigSecret.github_app_installation_id
    - kind: Secret
      name: actions-runner-controller-auth-secret
      valuesKey: github_app_private_key
      targetPath: githubConfigSecret.github_app_private_key
