---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghostfolio-redis
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s2
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 8.2.1@sha256:cc2dfb8f5151da2684b4a09bd04b567f92d07591d91980eb3eca21df07e12760
            env:
              REDIS_REPLICATION_MODE: master
            resources:
              requests:
                cpu: 5m
                memory: 256M
              limits:
                memory: 256M
    service:
      main:
        ports:
          http:
            enabled: false
          redis:
            enabled: true
            port: 6379
