apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
- helmrelease.yaml
- externalsecret.yaml
configMapGenerator:
- files:
  - config/config.ini
  name: obsidian-couchdb-configmap
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  disableNameSuffixHash: true
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: obsidian-couchdb
    app.kubernetes.io/name: obsidian-couchdb
