---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: actual
  namespace: default
  annotations:
    tailscale.com/expose: "true"
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s2
        namespace: flux-system

  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: data
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: local-path
              globalMounts:
                - path: /data

#        pod:
#          enableServiceLinks: false
#          securityContext:
#            runAsUser: 568
#            runAsGroup: 568
#            fsGroup: 568
#            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 23.10.0
            resources:
              requests:
                cpu: 12m
                memory: 128M
              limits:
                memory: 512M

    service:
      main:
        ports:
          http:
            port: 5006

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.mambalab.live
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Selfhosted
          gethomepage.dev/name: Actual
          gethomepage.dev/icon: https://raw.githubusercontent.com/Jas-SinghFSU/homepage-dracula/main/dracula_icons/actual.png

        hosts:
          - host: &host "{{ .Release.Name }}.mambalab.live"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
