---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: kube-cleanup-operator
  app.kubernetes.io/instance: kube-cleanup-operator
