---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-obsidian-couchdb
  namespace: flux-system
spec:
  interval: 10m
  path: "./cluster/apps/selfhosted/obsidian-couchdb/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    #    - name: cluster-apps-longhorn
