---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s2
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.3
            env:
              TZ: "America/NEW_YORK"
            resources:
              requests:
                cpu: 100m
                memory: 52M
              limits:
                memory: 128M
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.mambalab.live"
        hosts:
          - host: &host "uptime.mambalab.live"
            paths:
              - path: "/"
                pathType: "Prefix"
                service:
                  name: main
        tls:
          - hosts:
              *host
    persistence:
      data:
        enabled: true
        globalMounts:
          - path: /app/data
        storageClass: local-path
        accessMode: ReadWriteMany
        size: 2Gi
        retain: true