---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s2
        namespace: flux-system
      interval: 15m
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.3
            env:
              TZ: "America/New_York"
            resources:
              requests:
                cpu: 100m
                memory: 250M
              limits:
                memory: 1000M
    service:
      main:
        ports:
          http:
            port: &port "3001"
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.mambalab.live
        hosts:
          - host: &host "uptime.mambalab.live"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /healthcheck
            port: *port
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
      readiness: *probes

    persistence:
      data:
        enabled: true
        globalMounts:
          - path: /app/data
        existingClaim: uptime-kuma-data
