---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app uptime-kuma
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: louislam/uptime-kuma
      tag: 1.23.3
    service:
      main:
        ports:
          http:
            port: 3001
    persistence:
      config:
        enabled: true
        existingClaim: uptime-kuma-data
        mountPath: /app/data
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.mambalab.live"
        hosts:
          - host: &host "uptime.mambalab.live"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        memory: 1000Mi
