---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app tailscale
  namespace: networking
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s2
        namespace: flux-system
      version: 2.0.3
  install:
    remediation:
      retries: 3
  interval: 30m
  maxHistory: 2
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            env:
              PORT: &port 45387
              TS_ROUTES: "10.42.0.0/16,192.168.1.0/24"
              TS_EXTRA_ARGS: "--advertise-exit-node"
              TS_USERSPACE: "true"
              TZ: "America/New_York"
            envFrom:
              - secretRef:
                  name: tailscale-operator-secret
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.50.1
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
        pod:
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
    service:
      main:
        ports:
          http:
            port: 2000
      tailnet:
        controller: main
        ports:
          tailnet-udp:
            enabled: true
            port: *port
            protocol: UDP
    serviceAccount:
      name: tailscale
