---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s2
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 4
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 4
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.50.1
            env:
              TZ: "America/New_York"
              PORT: &port 45387
              SA_NAME: tailscale
              TS_USERSPACE: true
              TS_KUBE_SECRET: tailscale-state
              TS_TAILSCALED_EXTRA_ARGS: --debug=0.0.0.0:2000
              TS_ROUTES: "192.168.1.0/24,10.42.0.0/16,10.43.0.0/16"
            envFrom:
              - secretRef:
                  name: tailscale-secret
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 256M
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
    service:
      main:
        ports:
          http:
            port: 2000
      tailnet:
        controller: main
        type: LoadBalancer
        annotations:
          metallb.universetf/loadBalancerIPs: 192.168.1.232
        ports:
          tailnet-udp:
            enabled: true
            port: *port
            protocol: UDP
    serviceAccount:
      name: tailscale
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /debug/metrics
            interval: 1m
            scrapeTimeout: 30s
