---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-configmap
  namespace: default
data:
  # Configure application
  PAPERLESS_URL: https://paperless.mambalab.live
  PAPERLESS_PORT: "8000"
  PAPERLESS_TIME_ZONE: "America/New_York"
  PAPERLESS_WEBSERVER_WORKERS: "2"
  PAPERLESS_TASK_WORKERS: "2"

  # Configure folders
  PAPERLESS_CONSUMPTION_DIR: /data/longhorn/consume
  PAPERLESS_DATA_DIR: /data/longhorn/data
#  PAPERLESS_EXPORT_DIR: /data/nas/export
  PAPERLESS_MEDIA_ROOT: /data/longhorn/media

  # Configure folder importer
  PAPERLESS_CONSUMER_POLLING: "60"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"

  # Configure OCR
  PAPERLESS_OCR_LANGUAGES: eng
  PAPERLESS_OCR_LANGUAGE: eng

  # Configure redis integration
  PAPERLESS_REDIS: redis://paperless-redis.selfhosted.svc.cluster.local:6379

  # Configure user permissions
  #USERMAP_GID: "65543"