apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # Specify the Longhorn storage class
  resources:
    requests:
      storage: 15Gi  # Request the desired storage size
