---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: selfhosted
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/binwiederhier/ntfy
              tag: v2.7.0
            args: ["serve"]
            env:
              TZ: "AMERICA/NEW_YORK"
              NTFY_DEBUG: true
              NTFY_LOG_LEVEL: "DEBUG"
              NTFY_BEHIND_PROXY: "true"
              NTFY_LISTEN_HTTP: ":8080"
              NTFY_BASE_URL: "https://nfty.mambalab.live"
              NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh"
              PORT: &port 8080
            resources:
              requests:
                cpu: 500m
                memory: 250Mi
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames: 
          - ntfy.mambalab.live
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
#    ingress:
#      main:
#        enabled: true
#        className: internal
#        annotations:
#          external-dns.alpha.kubernetes.io/target: "internal.mambalab.live"
#        hosts:
#          - host: &host "ntfy.mambalab.live"
 #           paths:
 #             - path: /
 #               pathType: Prefix
 #               service:
 #                 name: main
 #                 port: http
 #       tls:
 #         - hosts:
 #           - *host
    persistance:
      config:
        enabled: true
        type: configMap
        name: server-config
        mountPath: /etc/ntfy/server.yaml
      cache:
        enabled: true
        type: pvc
        mountPath: /var/cache/ntfy
        storageClass: ntfy-config
