---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
resources:
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
    - name: server-config
      files:
        - ./server.yaml
generatorOptions:
  disableNameSuffixHash: true
