apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-config
  namespace: selfhosted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-config  # Specify the Longhorn storage class
  resources:
    requests:
      storage: 1Gi
