---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s2
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/haraldkoch/excalidraw
      tag: latest@sha256:cb3779395c51500351affce38c1fc1e4121bff03e1ca704c3adb1bbdc748bbe0
    service:
      main:
        ports:
          http:
            port: 8080
            targetPort: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.mambalab.live
        hosts:
          - host: &host "draw.mambalab.live"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    resources:
      requests:
        cpu: 5m
        memory: 15M
      limits:
        memory: 15M
