apiVersion: v1
data:
    access-key: ENC[AES256_GCM,data:rLiF6ynK/vDXeNAobwfK4GzTFy0=,iv:17Oph+ZiABzxBxlerlB0NBOlXZxUigzE4AvF6J+mHLA=,tag:uyjh19xgUsg/MF13B5MS3w==,type:str]
    secret-access-key: ENC[AES256_GCM,data:DrRZp3fu6lNkYqfHo+E2d2+V4tRZVBrOlt4hnCxKMUTehDqfGfHZmQ==,iv:Mdf258g6Y5p3gSyAvliNmyXTXpT7jEX6tgQKZrNwTYk=,tag:6UuFIZNS10L6NigeGhPAkQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: awssm-secret
    namespace: kube-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fema8gdj73k0hgk7s7h23uavm3mh3smst5eqq0sw8cfcakmxpa6q9pzftc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdUV3V2g5N0p4elM2VTI4
            SWVmME1ha3NCbFlIZjgvZllZNnFmY2dsY0ZRClo3TTRmZm5GUXNQWkhQaVBSelRS
            RitQa3VCUEs3U2Fic3lBOXZlZGNPOTAKLS0tIHNXZTlsZDZoV1Zua0NoelAxdWZW
            MVl4WFdvQzZFRVlOZDlWcVZUSE1mbDAKEJH30ORDx4GN0w9jF+t8YL139B0gW2Gz
            7qYe3jTVTdht6UNu2VCObhwMiHl12VUdFj7P9nlg3580UN895hSI5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T18:17:59Z"
    mac: ENC[AES256_GCM,data:g+Bq6jZfj7B99lwt5u6zLBrkzlfIQrzHG8fdlF4xJXEmt51nDCmsSWsqvvQDKF4l9tZHRXHgtcq1O0D1BqetqryB3tx+VQ7wbrNrBq45fg/2b4zCQ+IB9fb0BVVBOcdfgrBMZUoma6Uc3XaYW/qKyE17ry+VSEtKnvoIj9sHMe4=,iv:9MKkN8P8yXbX80NAu9R5IYVim4r/8tj1GJ76z76LY5A=,tag:VFKqTEhZwLk1DrYXsuI5SA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
