# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:KYRL8Nknmva4dofB7wkN6ZQL9Yv6nPEBQHYWso8BWO9TXEtxrXrJ/w==,iv:/U4nAtk0mzSnx0UNnTAEMWYEhMZw+mjRW6HBIEwZGvo=,tag:SRdgWePDYQCpKVL22ILKzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fema8gdj73k0hgk7s7h23uavm3mh3smst5eqq0sw8cfcakmxpa6q9pzftc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4THJXQUtBRHVlZmtPUjVM
            YWxqTFdVOElVOGxId0VucVZTZUozSkJ5blNrCmMxbnFlVHVGclBhMnJYbVIyUjVP
            Um9OeFJib21heVVMQUVnU1IvT0czMTgKLS0tIHg2MGVGWlpaekoxZWd5dW9Gcm5C
            bXh1dWFRSVcybVhFQVIvem1Nc28wcjgKyEfjjhNz8cXVlnkUKzAcMYy5o+I+pqnO
            Ze91IG0eM1e5oUmktfL5wcJckjWzZBOAmK1Us9eI//CrVNJ9lvKugg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-22T11:53:17Z"
    mac: ENC[AES256_GCM,data:K5vx0NrptMo1C3UHTWJ3R1BZojhxWg+vSUXglerN84i2N7I3CkicOKMsXHh19JytQVGm5W7KdiQwfYYaQdK+va/KyitQtC7zykkhNBMxUlJuUb6PK5UcWjqSCBB2Dt8hLYFMt2Obw2FOxkTE6HU+WSTMlTDlmiHld0MXI/nNItM=,iv:azYzItfDbfJgF4oqVBRu4hc/zdDRJZWhBjUy58JXRAE=,tag:/L37rpH8wvkc0t9W0GCSPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
