---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: miniflux
  namespace: selfhosted
spec:
  postgresVersion: 15
  instances:
    - dataVolumeClaimSpec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

  users:
    - name: miniflux
      databases:
        - miniflux
      options: "SUPERUSER"


  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
          - --type=full
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: longhorn-database
              accessModes:
              - "ReadWriteOnce"
              resources:
                requests:
                  storage: 5Gi
