---
warp-routing:
  enabled: true

# Top-level configuration
originRequest:
  http2Origin: true
  noTLSVerify: true

tunnel: kubernetes

credentials-file: /etc/cloudflared/credential.json
ingress:
  - hostname: "*.mambalab.live"
    service: &svc http://cilium-gateway-external.kube-system.svc.cluster.local:80
  - hostname: mambalab.live
    service: *svc
    originRequest:
      originServerName: external.mambalab.live
  - service: http_status:404
