---
ingress:
  - hostname: "*.mambalab.live"
    service: https://nginx-external-controller.networking.svc.cluster.local:443
    originRequest:
      originServerName: external.mambalab.live
  - service: http_status:404