---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 4
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 4
  uninstall:
    keepHistory: false
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    defaultSettings:
#      backupTarget: s3://longhorn@us-west-2/
#      backupTargetCredentialSecret: longhorn-secret
      defaultReplicaCount: 3
      backupstorePollInterval: 0
      createDefaultDiskLabeledNodes: true
      defaultDataPath: /data/longhorn
      restoreVolumeRecurringJobs: true
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 1
      guaranteedEngineManagerCPU: 20
      guaranteedReplicaManagerCPU: 20
      orphanAutoDeletion: true
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
    ingress:
      enabled: true
      ingressClassName: internal
      # annotations:
      #   gethomepage.dev/enabled: "true"
      #   gethomepage.dev/icon: longhorn.png
      #   gethomepage.dev/name: Longhorn
      #   gethomepage.dev/group: Infrastructure
      #   gethomepage.dev/widget.type: longhorn
      #   gethomepage.dev/widget.url: http://longhorn-frontend.storage
      host: longhorn.mambalab.live
      tls: true
