---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-database
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  diskSelector: "ssd,fast"
  nodeSelector: "storage"

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-config
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  diskSelector: "ssd,fast"
  nodeSelector: "storage"
