apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:NX+CY2uXTQ2ePvjM2ryV7/MdNfcejB9/FA==,iv:4Bh4fyP1rIsq9sxzQ+NKwjV+4QOAQH0AH7Is4aratng=,tag:gWTLJ9Ag/2+2kcso7Ub0QQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:/lrTJubbAKPnodLkug==,iv:kH44JZLBk4tP1RyRMbIzuwQGLNkjYFemA014hSdhDV0=,tag:en7R2nY2mPvpizktplnEWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fema8gdj73k0hgk7s7h23uavm3mh3smst5eqq0sw8cfcakmxpa6q9pzftc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd0xqWEpXeU5XZnR0eGZU
            N1dUU2ZvRkp2Z1Nzczg5cTNVc2JaYVZONFNRClk4ZWF1bVk2MElrVkdVajloTzlx
            TytYem8ybjlyKzhvbXZGSXNwRkVsQVEKLS0tIGsrQWtNa0ZlYS8ySzhsbWVDdDlR
            WW4yY1lOb1RiYnBxZ0VZVUlYcVVLRm8KX2uWt9uMswI5JafdRYLUl2Bj7Tk3yd8d
            XGnVgxf1hzbargowSfSA6PyXOBH15dHUuBOkGW5T1Wi6J0gnzfptgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T14:39:45Z"
    mac: ENC[AES256_GCM,data:14Fn/ABsbDGfOMH1KP4Ra1qFGsgwy7mGkLlsabsqOmJdRfDWngTIryajBnvafGormUOzIH8CCH+Z1LX8sQIvL2Msexx18QKhCOtCX7fVz0WqQbZfjWbKeEuClke0JmZkL0NOezsfjS2wUoojnn3kGHb4gk0YjEjHyd76It77p+s=,iv:WPSA9TSQmgGaFUwu/8E+o0vsaIbMLJ7QiS/NgYgfvZg=,tag:VN6wrzGxIpHgnjuc7RMsJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
