apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api_key: ENC[AES256_GCM,data:NAx8rXUcyewKb56mLivqirKH6EZ4V0uBA0dWaYsKxWjTwobtXoYVzg==,iv:DsvwftZoTd8nBT2zTOwzEz6V3nqEwh65MV48VHREHXw=,tag:Cou+pMTVg2JTjKs0btFL2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fema8gdj73k0hgk7s7h23uavm3mh3smst5eqq0sw8cfcakmxpa6q9pzftc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWnNhZU5TbXpPSWtlTzVC
            c1JVSVg5Nk45U1NVMUJkN0JoWVl4SXJnd3c0CjhGRCtlaGlZNjZ4dzFSMW9JSm0r
            U0x0MUJ3ck81T0ZGT0UwVjloVXhoMW8KLS0tIFlNMTVpSnhWbVZDR2d4aEFVSGx3
            L0hQMjdKeHZqVVh5OWNjcDFYL0VXUW8KLubkHKiXTRIKrVK8RkZ07UHSyfTSqLRj
            K/3Si/00DPG0zu1so7Sh9xl8kxnXTQC1+yarn2ttvy5fmPgYITRwUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-06T16:15:33Z"
    mac: ENC[AES256_GCM,data:S/AIf1Y3clVqyjPqIIbsVhb9O4wJ2OPTcc+NMgrI3my13bKL4m7vM9FzamBh/CZkl0KpL5jpvmcoUPNECMwhKiMQIC7+RRMioGtVAcfZP3F4Aloz85S/N+zW55ShuVgrvOzlZU5TAdQ11IxpbRr7ngZMrH7+3ser+KhpY6CX77M=,iv:MX4ATniZJ5W2R5UHeXqSJh6ZkrzaBwNlOtF5MkrCPdo=,tag:7xkxhQ36N7lR7nIJZkrpQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
