---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./rbac.yaml
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: gatus-configmap
    namespace: monitoring
    files:
      - config.yaml=./config/config.yaml
generatorOptions:
  disableNameSuffixHash: true
