---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-couchdb
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: obsidian-sync-secret
    creationPolicy: Owner
  data:
    - secretKey: couchdb-user
      remoteRef:
        key: obsidian
        property: couchdb_username
    - secretKey: couchdb-password
      remoteRef:
        key: obsidian
        property: couchdb_password
