---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: obsidian-couchdb
  namespace: selfhosted
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: obsidian-couchdb-secret
    creationPolicy: Owner
dataFrom:
    - extract:
        # COUCHDB_USER, COUCHDB_PASSWORD
        key: obsidian