---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-mambalab-live
  namespace: default
spec:
  secretName: local-mambalab-live-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.mambalab.live"
  dnsNames:
  - "local.mambalab.live"
  - "*.local.mambalab.live"